### ISSUE TITLE
请问可以升级Rails6版本的吗？

### ISSUE THREAD

**Issue by rubyyc** [mycolorway/activestorage_qiniu#23]
看了下，这个支持rails5，但不支持rails6，希望作者能再出个rails6版本的，非常感谢

**Comment by layerssss** [comment]
848176393587d02848639f8f4f2dd5c4c92c61a7 已经 fix 了只是还没发布到 rubygems.org 上， @ichord  能帮忙联系维护者发布吗？

目前暂时可以这样安装从 github 上安装最新的版本 @rubyyc 

```
gem 'activestorage_qiniu', git: 'https://github.com/mycolorway/activestorage_qiniu.git', branch: 'master'
```

**Comment by ichord** [comment]
@seandong 抽空发布一下吧。

**Comment by seandong** [comment]
@layerssss 已发布到 rubygems.org 了，感谢反馈 ~
